[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "Unicode-3.0",
    "MPL-2.0"
]

[bans]
multiple-versions = "warn"
highlight = "all"

[advisories]
db-path = "~/.cargo/advisory-dbs"
db-urls = ["https://github.com/RustSec/advisory-db"]
unmaintained = "all"
unsound = "all"
