name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
          
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          
      - name: Install system dependencies
        run: sudo apt-get update
        
      - name: Install Rust
        run: rustup update stable
        
      - name: Install wasm target
        run: rustup target add wasm32-wasip2

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true
        
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
        
      - name: Generate code coverage
        run: cargo llvm-cov --html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/llvm-cov/html
          publish_branch: gh-pages
